### PR TITLE
'Punishment' Mod

### PR DESCRIPTION
**Pull request by zarradeth**
This pull request adds a new mod to the project- the 'Punishment' mod.

This mod works together with an external force feedback device (this pull request contains an implementation for the PiShock) to trigger force feedback based on the player falling or making progress. The types of feedback generated (punishments and/or rewards) and their intensity/duration are all configurable. When used with a PiShock the player will be shocked (or optionally receive a vibration) in the event of a fall and will receive a vibration in the event of forward progress.

image

image

I've tried to follow code patterns/style used elsewhere in the project with these changes/additions. These changes don't pull any new packages into the project.  
The main additions in this request are:
####  PBJKModBase.FeedbackDevice.Settings, PBJKModBase.PiShock, and PBJKModBase.PiShock.Settings
These work similarly to the existing PBJKModBase.Streaming.Settings, PBJKModBase.Twitch, PBJKModBase.Twitch.Settings, and related projects. They exist to allow selecting a feedback device you would like to use (for potential future support of other devices/APIs) as well as classes for configuring, instantiating, and interacting with a PiShock device in other code.
#### JumpKingPunishmentMod and JumpKingPunishmentMod.Settings
These contain the actual logic for the mod and its settings- these work similarly to the other existing (RavensMod and ModifiersMod) projects. Most of the important logic for the mod itself is handled by PunishmentManagerEntity.cs. Interaction with a feedback device does use an abstraction within JumpKingPunishmentMod (IPunishmentDevice.cs) to, again, potentially support other devices/APIs in the future.
#### JumpKingMod.Install.UI
The installer has been updated with the Feedback device and PiShock settings (similar to the Streaming Platform and Twitch settings) as well as adding the Punishment Mod settings.
#### Documentation Updates
This pull request includes updates to the Readme and GettingStarted guide with details on the new mod, as well as new documentation pages specific to Feedback device setup and the Punishment mod settings. (I also swapped all inter-document links in the documentation to be relative so they work properly regardless of the repository.)

### CODE REVIEW

**Comment by PhantomBadger** [comment]
Hey @zarradeth! Sorry for the late reply I missed the notification.

Thanks for making a Pull Request! It's really cool to see someone expand on my mod like this, i hope the code wasnt too painful to work with haha.

Unfortunately I'm not actively maintaining this repo currently, as such I have mixed feelings about accepting a PR at this time if I don't have the time to then properly manage its state post-merge. That is subject to change in the coming months as some other work I'm doing clears up so I'll reach out :) 

I'd encourage you to do your own release of your fork however in the meantime! It would be awesome to see this out in the wild and in use by people, let me know if I can help at all with that (I'd love to spread the word however I could)!

**Comment by zarradeth** [comment]
@PhantomBadger 
No worries, to be fair too I've still been making changes to this pull request since I originally opened it (I thought I was done with it when I made the pull request, but I've still been improving it- I'm hoping I'm about done at this point though minus any bug fixes).

I understand your reasoning for not merging this yet, if you do get back to this repro though I would love to work together to get this merged (maintaining/having multiple different releases of this project seems undesirable for a couple reason). Just reach out to me on this pull request whenever/if you are ready. I also understand if you ultimately decide to not take this given the maintenance responsibility that comes with that and that this is kinda just me sticking a new mod into your work/framework and less improvements to the work you already have here.

Thanks for the okay doing my own release of the fork! I felt a bit weird doing that since most of the work/mods in the release is still yours but given the circumstances and your approval I will do that in the near future!
Thanks!

**Comment by PhantomBadger** [comment]
@zarradeth 
If push comes to shove you can always disable/hide the 'base' parts of the mod by commenting out the creation/registration in JumpKingModifiersModEntry.cs - I don't particularly mind as long as you give me some credit for it :) 

I'll likely be revisiting this for some tangential work within the next month so I'll let you know when that becomes more public and we can figure out where its best for this to live

**Comment by PhantomBadger** [comment]
@zarradeth Sorry wasn't able to share details sooner: https://twitter.com/nexilegames/status/1758567536138846644 (NDAs woo!) I'll be looking to port the Ravens and parts of the Modifiers mod (Lava and Fall Damage at least probably) in the coming weeks, I wrote the Mod API so happy to assist in answering any questions if you want to also port your Punishment Mod to the official workshop :) 

Happy to review this more formally this week and get it merged in regardless though, so let me know how you want to proceed!

**Comment by zarradeth** [comment]
@PhantomBadger 
Thanks for the heads up! I will take a look at the official modding stuff and what it would take to port to that. If I'm able to replicate all of the functionality I need within that I will probably just do a workshop release over the standalone mod and this merge won't be needed anymore/the workshop release will supersede the standalone version.

**Comment by zarradeth** [comment]
Closing this pull request out- this mod has been reimplemented as a standalone mod using the new official mod support- thus this version of the mod is no longer needed/this pull request is no longer relevant.

Thanks for all the help with this!

**Pull request closed without merging**
